server:
  port : 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vending_machine_db?useUnicode=true&serverTimezone=UTC
    username: root
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver


flyway:
  url: ${db.url}
  user: ${db.username}
  password: ${db.password}
  schemas: vending_machine_db
  table: flyway_schema_history
  locations: filesystem:db/migration
  out-of-order: true
  baseline-version: 0
  baseline-on-migrate: true
